### ISSUE TITLE
question about EMI 1.18.2 forgebackport. Did you get it working?

### ISSUE THREAD

**Issue by TheSaltyGaming** [ManuWar73/Remodeled_industry-#7]
Hi, turns out i'm not able to add an issue on a forked repo, but I was just wondering if you ever got the EMI 1.18.2 forge backport to work. I saw you did some changes on one of the branches, and i tried building it myself, but I just keep running into errors.

Did you ever get it working? And if so, do you happen to have a jar file that you're willing to share? It would mean a lot if you did!!!!

**Comment by ManuWar73** [comment]
Well, i never did. I tried to understand what a mapping was, and got so confused to the point that I gave up. Ive never modded minecraft, and starting by backporting a mod was not a good idea to start with...
